version: '3.3'
services:

  app:
    build:
      context: ./app/
      dockerfile: Dockerfile 
    restart: on-failure
    command: sh -c "sleep 15 && python3 /app/app.py"
    ports:
      - '3000:5000'
    depends_on:
      - db
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'ROOT'
      MYSQL_HOST: 'db'
      MYSQL_PORT: '3306'
      MYSQL_DATABASE: 'db'
    networks:
      - mynetwork

  db:
    build:
      context: ./db
      dockerfile: Dockerfile  
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'ROOT'
    expose:
      - 3306
    ports:
      - '3307:3306'
    networks:
      - mynetwork

networks:
  mynetwork:
   
    

